name: Build Windows Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        # Create a virtual environment
        python -m venv venv
        # Activate the virtual environment
        .\venv\Scripts\activate
        # Install dependencies (if any)
        pip install -r requirements.txt
        # Build the Windows executable
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: dist/main.exe
    
    - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_NAME: ${{ steps.extract_names.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.extract_names.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.extract_names.outputs.SOURCE_TAG }}
        with:
          files: dist/main.exe
    
