name: Build Windows Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        # Create a virtual environment
        python -m venv venv
        # Activate the virtual environment
        .\venv\Scripts\activate
        # Install dependencies (if any)
        pip install -r requirements.txt
        # Build the Windows executable
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/main.exe
